
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS ID NUMBER PLUS SEMICOLONprogram : statement_liststatement_list : statement\n                      | statement_list statementstatement : assignment_statementassignment_statement : ID EQUALS expression SEMICOLONexpression : expression PLUS termexpression : termterm : NUMBERterm : ID'
    
_lr_action_items = {'ID':([0,2,3,4,6,7,12,13,],[5,5,-2,-4,-3,8,-5,8,]),'$end':([1,2,3,4,6,12,],[0,-1,-2,-4,-3,-5,]),'EQUALS':([5,],[7,]),'NUMBER':([7,13,],[11,11,]),'SEMICOLON':([8,9,10,11,14,],[-9,12,-7,-8,-6,]),'PLUS':([8,9,10,11,14,],[-9,13,-7,-8,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'statement_list':([0,],[2,]),'statement':([0,2,],[3,6,]),'assignment_statement':([0,2,],[4,4,]),'expression':([7,],[9,]),'term':([7,13,],[10,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> statement_list','program',1,'p_program','parser_1.py',17),
  ('statement_list -> statement','statement_list',1,'p_statement_list','parser_1.py',21),
  ('statement_list -> statement_list statement','statement_list',2,'p_statement_list','parser_1.py',22),
  ('statement -> assignment_statement','statement',1,'p_statement','parser_1.py',29),
  ('assignment_statement -> ID EQUALS expression SEMICOLON','assignment_statement',4,'p_assignment_statement','parser_1.py',33),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser_1.py',38),
  ('expression -> term','expression',1,'p_expression_term','parser_1.py',42),
  ('term -> NUMBER','term',1,'p_term_number','parser_1.py',46),
  ('term -> ID','term',1,'p_term_id','parser_1.py',50),
]
